services:
  db:
    image: postgres:17
    container_name: epi-sign-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - epi-sign
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epi-sign-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      JWT_SECRET: secret
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - epi-sign

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: epi-sign-frontend
    ports:
      - "8081:80"
    networks:
      - epi-sign

networks:
  epi-sign:
    name: epi-sign
    driver: bridge
